file_hosting/urls.py
#from django.contrib import admin
from django.urls import path, include


urlpatterns = [
#    path('admin/', admin.site.urls),
    path('', include('files.urls')),
]

files/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'files'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_file, name='add'),
    path('add-after/', views.add_file_after, name='add_after'),
    path('del/', views.del_file, name='del'),
    path('del-after/', views.del_file_after, name='del_after'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse, HttpResponseBadRequest

from .file_storage import FileStorage, _create_file_object_from_json, _create_file_object_from_post

# Create your views here.


def index(request):
    """Выдаёт список файлов"""
    files = FileStorage().list()

    if request.is_ajax():
        return JsonResponse(files, safe=False)
    else:
        return render(request, 'files/index.html', {'files': files})


def del_file(request):
    """Удаляет файл из директории"""
    if not request.method == 'POST':
        return HttpResponseBadRequest()

    name = request.POST.get('filename')
    if not name:
        raise Http404()

    result = FileStorage().delete(name)

    if request.is_ajax():
        return JsonResponse({'result': 'Ok'})
    else:
        return HttpResponseRedirect(reverse_lazy('files:del_after'))


def del_file_after(request):
    return render(request, 'files/del-after.html')


def add_file(request):
    """Добавляет новый файл в директорию"""
    if not request.method == 'POST':
        return HttpResponseBadRequest()

    if request.FILES:
        file_object = _create_file_object_from_post(request.FILES['file'])
    # elif request.is_ajax() :
    #     file_object = _create_file_object_from_json(request.body)
    else:
        return HttpResponseBadRequest()

    name, content = file_object

    result = FileStorage().save(name, content)

    if request.is_ajax():
        return JsonResponse({'result': 'Ok'})
    else:
        return HttpResponseRedirect(reverse_lazy('files:add_after'))


def add_file_after(request):
    return render(request, 'files/add-after.html')

# def show_file(request, name):
#     """Возвращает страницу с отдельным файлом"""
#     if not name:
#         return Http404
#
#     if request.is_ajax():
#         file_content = FileStorage().get_file_content(name)
#         return JsonResponse(request, {'file': file_content})
#     else:
#         file_url = FileStorage().get_file_url(name)
#         return render(request, 'files/view.html', {'file_url': file_url})

files/templates/files/add-after.html
{% extends 'files/base.html' %}

{% block content %}
	<h2>Файл был успешно добавлен</h2>
	<p><a href="{% url 'files:index' %}">Вернуться к списку файлов</a></p>
{% endblock %}

files/templates/files/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}Панель управления файлами на сервере{% endblock %}</title>
</head>
<body>
	<div>
{% block content %}{% endblock %}
	</div>
{% block javascript %}{% endblock %}
</body>
</html>

files/templates/files/del-after.html
{% extends 'files/base.html' %}

{% block content %}
	<h2>Файл был успешно удалён</h2>
	<p><a href="{% url 'files:index' %}">Вернуться к списку файлов</a></p>
{% endblock %}

files/templates/files/index.html
{% extends 'files/base.html' %}
{% load static %}

{% block content %}
<h2>Файлы на сервере</h2>
<table class="files-table" >
<thead>
<tr>
	<th>Наименование</th>
	<th>Размер (байт)</th>
	<th></th>
</tr>
</thead>

<tbody id="f-list-table">
{% for f in files %}
<tr class="files-row" id="f-row-{{ f.id }}">
	<td class="file-name-outer"><a class="file-name" href="{{ f.url }}">{{ f.name }}</a></td>
	<td class="file-size">{{ f.size }}</td>
	<td class="buttons">
		<form method="post" action="{% url 'files:del' %}" class="file-del-form">
			{% csrf_token %}
			<input type="hidden" name="filename" value="{{ f.name }}" class="file-del-filename">
			<button type="submit" class="file-del">Удалить (без ajax)</button>
			<button type="button" class="file-del-ajax" id="f-del-{{ f.id }}">Удалить (ajax)</button>
		</form>
	</td>
</tr>
{% endfor %}
</tbody>
</table>


<form method="post" action="{% url 'files:add' %}" enctype="multipart/form-data">
{% csrf_token %}
<div>
	<h3>Добавить новый файл (без ajax)</h3>
	<input type="file" name="file" class="file-add-input">
	<button type="submit" class="file-add-btn">Загрузить</button>
</div>
</form>

<form method="post" action="{% url 'files:add' %}" enctype="multipart/form-data" id="f-add-form">
{% csrf_token %}
<div>
	<h3>Добавить новый файл (ajax)</h3>
	<input type="file" name="file" class="file-add-input" id="f-add-input">
	<button type="button" class="file-add-btn" id="f-add-btn">Загрузить</button>
</div>
</form>


{% endblock content %}

{% block javascript %}
	<script type="text/javascript" src="{% static 'js/files.js' %}"></script>
{% endblock javascript %}